l = ['a', 'b', 'c', 'd', 'e']
x = splice!(l, 3)
println(l)
println(x)
deleteat!(l, 3)
println(l)
y = popfirst!(l)
println(l)
println(y)
y = pop!(l)
println(l)
println(y)
push!(l, 'z')
println(l)
pushfirst!(l, 'p')
println(l)
insert!(l, 2, 'm')
println(l)
println(collect("spam"))
j = split("split this sentence into words")
println(j)
println(join(j, '-'))
